engines:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
      sonar.exclusions: ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-theme/**/*,ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/vendor/**/*
