version: "2"
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
exclude_patterns:
- "**/*.png"
- "**/*.jpeg"
- "**/*.jpg"
- "**/META-INF/"
- "**/clientlib-theme/"
- "**/vendor/"
- "**/apps/asset-share-commons/resources/"
- "**/content/dam/"
- "**/content/asset-share-commons/"
